// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlantsShopping.ProductAPI.Model.Context;

#nullable disable

namespace PlantsShopping.ProductAPI.Migrations
{
    [DbContext(typeof(PostgreContext))]
    [Migration("20260929003559_SeedPlantDataTable")]
    partial class SeedPlantDataTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlantsShopping.ProductAPI.Model.Plant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("plant");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "Planta de Interior",
                            Description = "Planta de interior muito popular, conhecida por suas folhas grandes e recortadas.<br/>Ideal para ambientes internos com luz indireta.<br/>Fácil de cuidar e excelente para dar um toque tropical na decoração da sua casa ou escritório.",
                            ImageUrl = "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?q=80&w=1000&auto=format&fit=crop",
                            Name = "Monstera Deliciosa (Costela-de-Adão)",
                            Price = 89.9m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Planta Pendente",
                            Description = "Clássica planta pendente com folhagem verde intensa e delicada.<br/>Gosta de ambientes úmidos e meia-sombra, sendo perfeita para varandas e áreas internas arejadas.<br/>Traga frescor e movimento para o seu espaço.",
                            ImageUrl = "https://images.unsplash.com/photo-1512428559087-560fa5ceab42?q=80&w=1000&auto=format&fit=crop",
                            Name = "Samambaia Americana",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Planta com Flor",
                            Description = "Conhecida por suas flores vistosas em formato de coração e brilho característico.<br/>Excelente para decorar salas e escritórios com muita elegância e cor.<br/>Prefere luz indireta e solo levemente úmido.",
                            ImageUrl = "https://images.unsplash.com/photo-1599598425947-4402690ff3c7?q=80&w=1000&auto=format&fit=crop",
                            Name = "Antúrio Vermelho",
                            Price = 59.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Suculentas",
                            Description = "Planta suculenta de pequeno porte, perfeita para mesas de trabalho e prateleiras.<br/>Requer pouca rega e bastante luminosidade.<br/>Um toque de verde delicado e de baixa manutenção para o seu dia a dia.",
                            ImageUrl = "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?q=80&w=1000&auto=format&fit=crop",
                            Name = "Suculenta Echeveria em Vaso Mini",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Planta de Interior",
                            Description = "Árvore de interior com folhas grandes, brilhantes e em formato de violino.<br/>Muito elegante, destaca-se em salas de estar amplas e varandas cobertas.<br/>Necessita de regas moderadas e luz solar indireta abundante.",
                            ImageUrl = "https://images.unsplash.com/photo-1545241047-6083a3684587?q=80&w=1000&auto=format&fit=crop",
                            Name = "Ficus Lyrata (Figueira-Bate-Folha)",
                            Price = 149.9m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Planta com Flor",
                            Description = "Famosa por suas elegantes flores brancas e folhagem verde escura brilhante.<br/>Excelente purificadora de ar para ambientes internos.<br/>Adapta-se muito bem a locais com menor incidência de luz solar direta.",
                            ImageUrl = "https://images.unsplash.com/photo-1593482834249-f0896792376d?q=80&w=1000&auto=format&fit=crop",
                            Name = "Lírio-da-Paz",
                            Price = 54.9m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Cactos",
                            Description = "Cacto ornamental de crescimento erguido e marcante, ideal para projetos paisagísticos e decorações modernas.<br/>Extremamente resistente e de baixíssima manutenção.<br/>Exige sol pleno ou luz direta intensa.",
                            ImageUrl = "https://images.unsplash.com/photo-1509205477838-a534e43a849f?q=80&w=1000&auto=format&fit=crop",
                            Name = "Cacto San Pedro",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Planta de Interior",
                            Description = "Surpreende pelos padrões geométricos únicos e tons de roxo na parte inferior de suas folhas.<br/>Gosta de ambientes úmidos, sombra parcial e solo leve.<br/>Um verdadeiro espetáculo de cores naturais para dentro de casa.",
                            ImageUrl = "https://images.unsplash.com/photo-1606856540909-6af86992d9d8?q=80&w=1000&auto=format&fit=crop",
                            Name = "Calathea Medallion (Planta-Pavão)",
                            Price = 79.9m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Planta Pendente",
                            Description = "Planta trepadeira resistente, ideal para cultivo em prateleiras altas ou suportes suspensos.<br/>Seus ramos pendentes criam um efeito cascata belíssimo.<br/>Extremamente adaptável a diferentes condições de luz interna.",
                            ImageUrl = "https://images.unsplash.com/photo-1598880940371-c756e015ba45?q=80&w=1000&auto=format&fit=crop",
                            Name = "Jiboia Verde (Epipremnum aureum)",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryName = "Planta de Interior",
                            Description = "Planta arbustiva de visual escultural e tronco robusto.<br/>Ótima opção para cantos de salas e áreas externas iluminadas.<br/>Resistente a períodos curtos de seca.",
                            ImageUrl = "https://images.unsplash.com/photo-1525498128493-380d1990a112?q=80&w=1000&auto=format&fit=crop",
                            Name = "Yucca Elephantipes (Yuca)",
                            Price = 119.9m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryName = "Planta de Interior",
                            Description = "Possui folhas marcantes com nervuras avermelhadas que se fecham à noite, como em sinal de prece.<br/>Perfeita para mesas de centro e aparadores com meia-luz.<br/>Adora umidade e carinho.",
                            ImageUrl = "https://images.unsplash.com/photo-1520302450370-7a2113d5b86f?q=80&w=1000&auto=format&fit=crop",
                            Name = "Maranta Leuconeura (Planta-Oração)",
                            Price = 45.9m
                        },
                        new
                        {
                            Id = 13L,
                            CategoryName = "Planta de Interior",
                            Description = "Conhecida por sua alta resistência, a zamioculca sobrevive bem em ambientes com pouca luz e regas esporádicas.<br/>Folhas verdes escuras com brilho natural impressionante.<br/>A planta perfeita para quem costuma esquecer de regar.",
                            ImageUrl = "https://images.unsplash.com/photo-1632834379967-a0ce5cb2544e?q=80&w=1000&auto=format&fit=crop",
                            Name = "Zamioculca em Vaso",
                            Price = 79.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
